#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI VII VIII
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config paddingless_monocle	true

bspc config active_border_color '#5e81ac'
bspc config normal_border_color '#4c566a'
bspc config focused_border_color '#5e81ac'


# bspc rule -a 'Alacritty' state=floating rectangle=1200x700+360+190

bspc rule -a 'discord' state=floating rectangle=1200x700+360+190
bspc rule -a 'vlc' state=floating rectangle=1200x700+360+190
bspc rule -a 'obs' state=floating rectangle=1200x700+360+190
bspc rule -a 'Thunar' state=floating rectangle=1200x700+360+190
bspc rule -a 'Engrampa' state=floating rectangle=1200x700+360+190 follow=off
bspc rule -a 'Viewnior' state=floating rectangle=1200x700+360+190

xsetroot -cursor_name left_ptr
/home/neurxez/.config/polybar/launch.sh &
picom -b &
nitrogen --restore &
nm-applet --no-agent &
