#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI VII VIII
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config single_monocle	true
bspc config borderless_monocle	true
bspc config gapless_monocle	false
bspc config paddingless_monocle	true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a 'firefox' desktop='^1' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a 'Alacritty' state=floating rectangle=1200x700+360+190

bspc rule -a 'discord' state=floating rectangle=1200x700+360+190
bspc rule -a 'Thunar' state=floating rectangle=1200x700+360+190
bspc rule -a 'Engrampa' state=floating rectangle=1200x700+360+190 follow=off
bspc rule -a 'Viewnior' state=floating rectangle=1200x700+360+190

/home/xnwerz/.config/polybar/launch.sh &
